// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/download/downloadpb/download.proto

package downloadpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileDownloadInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Extension            string   `protobuf:"bytes,3,opt,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileDownloadInfo) Reset()         { *m = FileDownloadInfo{} }
func (m *FileDownloadInfo) String() string { return proto.CompactTextString(m) }
func (*FileDownloadInfo) ProtoMessage()    {}
func (*FileDownloadInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b77e510c3925f8d, []int{0}
}

func (m *FileDownloadInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileDownloadInfo.Unmarshal(m, b)
}
func (m *FileDownloadInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileDownloadInfo.Marshal(b, m, deterministic)
}
func (m *FileDownloadInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileDownloadInfo.Merge(m, src)
}
func (m *FileDownloadInfo) XXX_Size() int {
	return xxx_messageInfo_FileDownloadInfo.Size(m)
}
func (m *FileDownloadInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileDownloadInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileDownloadInfo proto.InternalMessageInfo

func (m *FileDownloadInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileDownloadInfo) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FileDownloadInfo) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

type FileDownloadBody struct {
	Bytes                []byte   `protobuf:"bytes,4,opt,name=bytes,proto3" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileDownloadBody) Reset()         { *m = FileDownloadBody{} }
func (m *FileDownloadBody) String() string { return proto.CompactTextString(m) }
func (*FileDownloadBody) ProtoMessage()    {}
func (*FileDownloadBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b77e510c3925f8d, []int{1}
}

func (m *FileDownloadBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileDownloadBody.Unmarshal(m, b)
}
func (m *FileDownloadBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileDownloadBody.Marshal(b, m, deterministic)
}
func (m *FileDownloadBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileDownloadBody.Merge(m, src)
}
func (m *FileDownloadBody) XXX_Size() int {
	return xxx_messageInfo_FileDownloadBody.Size(m)
}
func (m *FileDownloadBody) XXX_DiscardUnknown() {
	xxx_messageInfo_FileDownloadBody.DiscardUnknown(m)
}

var xxx_messageInfo_FileDownloadBody proto.InternalMessageInfo

func (m *FileDownloadBody) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

type FileDownloadResponse struct {
	Body                 *FileDownloadBody `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FileDownloadResponse) Reset()         { *m = FileDownloadResponse{} }
func (m *FileDownloadResponse) String() string { return proto.CompactTextString(m) }
func (*FileDownloadResponse) ProtoMessage()    {}
func (*FileDownloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b77e510c3925f8d, []int{2}
}

func (m *FileDownloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileDownloadResponse.Unmarshal(m, b)
}
func (m *FileDownloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileDownloadResponse.Marshal(b, m, deterministic)
}
func (m *FileDownloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileDownloadResponse.Merge(m, src)
}
func (m *FileDownloadResponse) XXX_Size() int {
	return xxx_messageInfo_FileDownloadResponse.Size(m)
}
func (m *FileDownloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileDownloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileDownloadResponse proto.InternalMessageInfo

func (m *FileDownloadResponse) GetBody() *FileDownloadBody {
	if m != nil {
		return m.Body
	}
	return nil
}

type FileDownloadRequest struct {
	FileID               int32    `protobuf:"varint,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Extension            string   `protobuf:"bytes,3,opt,name=extension,proto3" json:"extension,omitempty"`
	Path                 string   `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	FromPersonalFolder   bool     `protobuf:"varint,5,opt,name=fromPersonalFolder,proto3" json:"fromPersonalFolder,omitempty"`
	ExternalFolderId     string   `protobuf:"bytes,6,opt,name=externalFolderId,proto3" json:"externalFolderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileDownloadRequest) Reset()         { *m = FileDownloadRequest{} }
func (m *FileDownloadRequest) String() string { return proto.CompactTextString(m) }
func (*FileDownloadRequest) ProtoMessage()    {}
func (*FileDownloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b77e510c3925f8d, []int{3}
}

func (m *FileDownloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileDownloadRequest.Unmarshal(m, b)
}
func (m *FileDownloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileDownloadRequest.Marshal(b, m, deterministic)
}
func (m *FileDownloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileDownloadRequest.Merge(m, src)
}
func (m *FileDownloadRequest) XXX_Size() int {
	return xxx_messageInfo_FileDownloadRequest.Size(m)
}
func (m *FileDownloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileDownloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileDownloadRequest proto.InternalMessageInfo

func (m *FileDownloadRequest) GetFileID() int32 {
	if m != nil {
		return m.FileID
	}
	return 0
}

func (m *FileDownloadRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileDownloadRequest) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

func (m *FileDownloadRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FileDownloadRequest) GetFromPersonalFolder() bool {
	if m != nil {
		return m.FromPersonalFolder
	}
	return false
}

func (m *FileDownloadRequest) GetExternalFolderId() string {
	if m != nil {
		return m.ExternalFolderId
	}
	return ""
}

func init() {
	proto.RegisterType((*FileDownloadInfo)(nil), "download.FileDownloadInfo")
	proto.RegisterType((*FileDownloadBody)(nil), "download.FileDownloadBody")
	proto.RegisterType((*FileDownloadResponse)(nil), "download.FileDownloadResponse")
	proto.RegisterType((*FileDownloadRequest)(nil), "download.FileDownloadRequest")
}

func init() {
	proto.RegisterFile("pkg/download/downloadpb/download.proto", fileDescriptor_6b77e510c3925f8d)
}

var fileDescriptor_6b77e510c3925f8d = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x52, 0xcd, 0x4e, 0xb3, 0x40,
	0x14, 0xfd, 0xe8, 0x47, 0x9b, 0xf6, 0xca, 0xa2, 0x19, 0x1b, 0x33, 0x69, 0xd4, 0x18, 0x16, 0xa6,
	0x71, 0x81, 0xa6, 0xbe, 0x41, 0xd3, 0x90, 0xb0, 0xd3, 0x71, 0x63, 0xdc, 0x81, 0x5c, 0x2c, 0x91,
	0xce, 0xe0, 0x0c, 0xfe, 0xf4, 0x29, 0x7d, 0x25, 0x61, 0xa0, 0x53, 0xd0, 0xea, 0xee, 0x9e, 0x1f,
	0x4e, 0x38, 0x27, 0x03, 0xe7, 0xf9, 0xf3, 0xd3, 0x65, 0x2c, 0xde, 0x79, 0x26, 0xc2, 0xd8, 0x1c,
	0x79, 0x64, 0x4e, 0x2f, 0x97, 0xa2, 0x10, 0x64, 0xb8, 0xc5, 0xee, 0x3d, 0x8c, 0xfd, 0x34, 0xc3,
	0x65, 0x83, 0x03, 0x9e, 0x08, 0x42, 0xc0, 0xe6, 0xe1, 0x1a, 0xa9, 0x75, 0x66, 0xcd, 0x46, 0x4c,
	0xdf, 0x15, 0x97, 0x87, 0xc5, 0x8a, 0xf6, 0x6a, 0xae, 0xba, 0xc9, 0x31, 0x8c, 0xf0, 0xa3, 0x40,
	0xae, 0x52, 0xc1, 0xe9, 0x7f, 0x2d, 0xec, 0x08, 0x77, 0xd6, 0x4d, 0x5e, 0x88, 0x78, 0x43, 0x26,
	0xd0, 0x8f, 0x36, 0x05, 0x2a, 0x6a, 0x97, 0x6e, 0x87, 0xd5, 0xc0, 0xf5, 0x61, 0xd2, 0x76, 0x32,
	0x54, 0xb9, 0xe0, 0x0a, 0x89, 0x07, 0x76, 0x54, 0x7e, 0xa5, 0xff, 0xe3, 0x60, 0x3e, 0xf5, 0x4c,
	0x89, 0xef, 0xb9, 0x4c, 0xfb, 0xdc, 0x4f, 0x0b, 0x0e, 0xbb, 0x41, 0x2f, 0xaf, 0xa8, 0x0a, 0x72,
	0x04, 0x83, 0xa4, 0xa4, 0x83, 0xa5, 0x4e, 0xea, 0xb3, 0x06, 0x99, 0x9e, 0xbd, 0x56, 0xcf, 0x3f,
	0x3b, 0x99, 0x15, 0xec, 0xd6, 0x0a, 0x1e, 0x90, 0x44, 0x8a, 0xf5, 0x0d, 0x4a, 0x25, 0x78, 0x98,
	0xf9, 0x22, 0x8b, 0x51, 0xd2, 0x7e, 0xe9, 0x18, 0xb2, 0x3d, 0x0a, 0xb9, 0x80, 0x71, 0x15, 0x28,
	0x0d, 0x13, 0xc4, 0x74, 0xa0, 0xf3, 0x7e, 0xf0, 0xf3, 0x55, 0xb7, 0xd0, 0x1d, 0xca, 0xb7, 0xf4,
	0x11, 0xc9, 0x2d, 0x38, 0x5b, 0xaa, 0x92, 0xc9, 0xc9, 0xfe, 0x69, 0x9a, 0xfe, 0xd3, 0xd3, 0xdf,
	0xe4, 0x7a, 0x67, 0xf7, 0xdf, 0x95, 0xb5, 0x70, 0x1e, 0x60, 0xf7, 0x5c, 0xa2, 0x81, 0x7e, 0x26,
	0xd7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x46, 0x6d, 0x60, 0x50, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FileDownloadServiceClient is the client API for FileDownloadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileDownloadServiceClient interface {
	DownloadFile(ctx context.Context, in *FileDownloadRequest, opts ...grpc.CallOption) (FileDownloadService_DownloadFileClient, error)
}

type fileDownloadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileDownloadServiceClient(cc grpc.ClientConnInterface) FileDownloadServiceClient {
	return &fileDownloadServiceClient{cc}
}

func (c *fileDownloadServiceClient) DownloadFile(ctx context.Context, in *FileDownloadRequest, opts ...grpc.CallOption) (FileDownloadService_DownloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FileDownloadService_serviceDesc.Streams[0], "/download.FileDownloadService/DownloadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileDownloadServiceDownloadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FileDownloadService_DownloadFileClient interface {
	Recv() (*FileDownloadResponse, error)
	grpc.ClientStream
}

type fileDownloadServiceDownloadFileClient struct {
	grpc.ClientStream
}

func (x *fileDownloadServiceDownloadFileClient) Recv() (*FileDownloadResponse, error) {
	m := new(FileDownloadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FileDownloadServiceServer is the server API for FileDownloadService service.
type FileDownloadServiceServer interface {
	DownloadFile(*FileDownloadRequest, FileDownloadService_DownloadFileServer) error
}

// UnimplementedFileDownloadServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFileDownloadServiceServer struct {
}

func (*UnimplementedFileDownloadServiceServer) DownloadFile(req *FileDownloadRequest, srv FileDownloadService_DownloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}

func RegisterFileDownloadServiceServer(s *grpc.Server, srv FileDownloadServiceServer) {
	s.RegisterService(&_FileDownloadService_serviceDesc, srv)
}

func _FileDownloadService_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileDownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileDownloadServiceServer).DownloadFile(m, &fileDownloadServiceDownloadFileServer{stream})
}

type FileDownloadService_DownloadFileServer interface {
	Send(*FileDownloadResponse) error
	grpc.ServerStream
}

type fileDownloadServiceDownloadFileServer struct {
	grpc.ServerStream
}

func (x *fileDownloadServiceDownloadFileServer) Send(m *FileDownloadResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _FileDownloadService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "download.FileDownloadService",
	HandlerType: (*FileDownloadServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadFile",
			Handler:       _FileDownloadService_DownloadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/download/downloadpb/download.proto",
}
